name: b34facfa-cea8-48f5-89f6-f11ce00812a9
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - jupyter
  - intake==0.7.*
  - intake-xarray==0.7.*
  - rioxarray==0.15.0
  - pytorch==1.8.0
  - torchvision==0.9.0
  - dask==2023.3.0
  - hvplot
  - pooch
  - pip
  - pip:
      - pycurl
      - scikit-image